//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapToRest.DiscountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscountInfo", Namespace="http://schemas.datacontract.org/2004/07/DiscountService")]
    [System.SerializableAttribute()]
    public partial class DiscountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscountRelationshipIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrganisationsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermsAndConditionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountRelationshipID {
            get {
                return this.DiscountRelationshipIDField;
            }
            set {
                if ((this.DiscountRelationshipIDField.Equals(value) != true)) {
                    this.DiscountRelationshipIDField = value;
                    this.RaisePropertyChanged("DiscountRelationshipID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountType {
            get {
                return this.DiscountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountTypeField, value) != true)) {
                    this.DiscountTypeField = value;
                    this.RaisePropertyChanged("DiscountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((this.ExpiryDateField.Equals(value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganisationsID {
            get {
                return this.OrganisationsIDField;
            }
            set {
                if ((this.OrganisationsIDField.Equals(value) != true)) {
                    this.OrganisationsIDField = value;
                    this.RaisePropertyChanged("OrganisationsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermsAndConditions {
            get {
                return this.TermsAndConditionsField;
            }
            set {
                if ((object.ReferenceEquals(this.TermsAndConditionsField, value) != true)) {
                    this.TermsAndConditionsField = value;
                    this.RaisePropertyChanged("TermsAndConditions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapToRest.DiscountService.ProductHasAttribute[] attributeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int groupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapToRest.DiscountService.ProductHasAttribute[] attributeList {
            get {
                return this.attributeListField;
            }
            set {
                if ((object.ReferenceEquals(this.attributeListField, value) != true)) {
                    this.attributeListField = value;
                    this.RaisePropertyChanged("attributeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                if ((this.categoryIdField.Equals(value) != true)) {
                    this.categoryIdField = value;
                    this.RaisePropertyChanged("categoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group {
            get {
                return this.groupField;
            }
            set {
                if ((object.ReferenceEquals(this.groupField, value) != true)) {
                    this.groupField = value;
                    this.RaisePropertyChanged("group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int groupId {
            get {
                return this.groupIdField;
            }
            set {
                if ((this.groupIdField.Equals(value) != true)) {
                    this.groupIdField = value;
                    this.RaisePropertyChanged("groupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int typeId {
            get {
                return this.typeIdField;
            }
            set {
                if ((this.typeIdField.Equals(value) != true)) {
                    this.typeIdField = value;
                    this.RaisePropertyChanged("typeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductHasAttribute", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class ProductHasAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int attributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int attributeId {
            get {
                return this.attributeIdField;
            }
            set {
                if ((this.attributeIdField.Equals(value) != true)) {
                    this.attributeIdField = value;
                    this.RaisePropertyChanged("attributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountService.IDiscounts")]
    public interface IDiscounts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetData", ReplyAction="http://tempuri.org/IDiscounts/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetData", ReplyAction="http://tempuri.org/IDiscounts/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductResponse")]
        void DeleteDiscountForProduct(int productID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductResponse")]
        System.Threading.Tasks.Task DeleteDiscountForProductAsync(int productID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductResponse")]
        void UpdateDiscountForProduct(int productID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductResponse")]
        System.Threading.Tasks.Task UpdateDiscountForProductAsync(int productID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductResponse")]
        void CreateDiscountForProduct(int productID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProduct", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductResponse")]
        System.Threading.Tasks.Task CreateDiscountForProductAsync(int productID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductgroupResponse")]
        void CreateDiscountForProductgroup(int groupID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductgroupResponse")]
        System.Threading.Tasks.Task CreateDiscountForProductgroupAsync(int groupID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductcategoryResponse")]
        void CreateDiscountForProductcategory(int CategoryID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProductcategoryResponse")]
        System.Threading.Tasks.Task CreateDiscountForProductcategoryAsync(int CategoryID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProducttypeResponse")]
        void CreateDiscountForProducttype(int typeID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountForProducttypeResponse")]
        System.Threading.Tasks.Task CreateDiscountForProducttypeAsync(int typeID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductgroupResponse")]
        void UpdateDiscountForProductgroup(int groupID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductgroupResponse")]
        System.Threading.Tasks.Task UpdateDiscountForProductgroupAsync(int groupID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductcategoryResponse")]
        void UpdateDiscountForProductcategory(int CategoryID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProductcategoryResponse")]
        System.Threading.Tasks.Task UpdateDiscountForProductcategoryAsync(int CategoryID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProducttypeResponse")]
        void UpdateDiscountForProducttype(int typeID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/UpdateDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/UpdateDiscountForProducttypeResponse")]
        System.Threading.Tasks.Task UpdateDiscountForProducttypeAsync(int typeID, int discountID, int percentUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductgroupResponse")]
        void DeleteDiscountForProductgroup(int groupID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProductgroup", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductgroupResponse")]
        System.Threading.Tasks.Task DeleteDiscountForProductgroupAsync(int groupID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductcategoryResponse")]
        void DeleteDiscountForProductcategory(int CategoryID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProductcategory", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProductcategoryResponse")]
        System.Threading.Tasks.Task DeleteDiscountForProductcategoryAsync(int CategoryID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProducttypeResponse")]
        void DeleteDiscountForProducttype(int typeID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscountForProducttype", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountForProducttypeResponse")]
        System.Threading.Tasks.Task DeleteDiscountForProducttypeAsync(int typeID, int discountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetOrganisationDiscounts", ReplyAction="http://tempuri.org/IDiscounts/GetOrganisationDiscountsResponse")]
        SoapToRest.DiscountService.DiscountInfo[] GetOrganisationDiscounts(int organisationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetOrganisationDiscounts", ReplyAction="http://tempuri.org/IDiscounts/GetOrganisationDiscountsResponse")]
        System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo[]> GetOrganisationDiscountsAsync(int organisationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetADiscountsProducts", ReplyAction="http://tempuri.org/IDiscounts/GetADiscountsProductsResponse")]
        SoapToRest.DiscountService.Product[] GetADiscountsProducts(int DiscountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetADiscountsProducts", ReplyAction="http://tempuri.org/IDiscounts/GetADiscountsProductsResponse")]
        System.Threading.Tasks.Task<SoapToRest.DiscountService.Product[]> GetADiscountsProductsAsync(int DiscountID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscount", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountResponse")]
        void CreateDiscount(SoapToRest.DiscountService.DiscountInfo Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/CreateDiscount", ReplyAction="http://tempuri.org/IDiscounts/CreateDiscountResponse")]
        System.Threading.Tasks.Task CreateDiscountAsync(SoapToRest.DiscountService.DiscountInfo Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/EditDiscount", ReplyAction="http://tempuri.org/IDiscounts/EditDiscountResponse")]
        void EditDiscount(SoapToRest.DiscountService.DiscountInfo Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/EditDiscount", ReplyAction="http://tempuri.org/IDiscounts/EditDiscountResponse")]
        System.Threading.Tasks.Task EditDiscountAsync(SoapToRest.DiscountService.DiscountInfo Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscount", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountResponse")]
        void DeleteDiscount(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/DeleteDiscount", ReplyAction="http://tempuri.org/IDiscounts/DeleteDiscountResponse")]
        System.Threading.Tasks.Task DeleteDiscountAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetDiscounts", ReplyAction="http://tempuri.org/IDiscounts/GetDiscountsResponse")]
        SoapToRest.DiscountService.DiscountInfo[] GetDiscounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetDiscounts", ReplyAction="http://tempuri.org/IDiscounts/GetDiscountsResponse")]
        System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo[]> GetDiscountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetDiscount", ReplyAction="http://tempuri.org/IDiscounts/GetDiscountResponse")]
        SoapToRest.DiscountService.DiscountInfo GetDiscount(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscounts/GetDiscount", ReplyAction="http://tempuri.org/IDiscounts/GetDiscountResponse")]
        System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo> GetDiscountAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiscountsChannel : SoapToRest.DiscountService.IDiscounts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountsClient : System.ServiceModel.ClientBase<SoapToRest.DiscountService.IDiscounts>, SoapToRest.DiscountService.IDiscounts {
        
        public DiscountsClient() {
        }
        
        public DiscountsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void DeleteDiscountForProduct(int productID, int discountID) {
            base.Channel.DeleteDiscountForProduct(productID, discountID);
        }
        
        public System.Threading.Tasks.Task DeleteDiscountForProductAsync(int productID, int discountID) {
            return base.Channel.DeleteDiscountForProductAsync(productID, discountID);
        }
        
        public void UpdateDiscountForProduct(int productID, int discountID, int percentUnit) {
            base.Channel.UpdateDiscountForProduct(productID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task UpdateDiscountForProductAsync(int productID, int discountID, int percentUnit) {
            return base.Channel.UpdateDiscountForProductAsync(productID, discountID, percentUnit);
        }
        
        public void CreateDiscountForProduct(int productID, int discountID, int percentUnit) {
            base.Channel.CreateDiscountForProduct(productID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task CreateDiscountForProductAsync(int productID, int discountID, int percentUnit) {
            return base.Channel.CreateDiscountForProductAsync(productID, discountID, percentUnit);
        }
        
        public void CreateDiscountForProductgroup(int groupID, int discountID, int percentUnit) {
            base.Channel.CreateDiscountForProductgroup(groupID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task CreateDiscountForProductgroupAsync(int groupID, int discountID, int percentUnit) {
            return base.Channel.CreateDiscountForProductgroupAsync(groupID, discountID, percentUnit);
        }
        
        public void CreateDiscountForProductcategory(int CategoryID, int discountID, int percentUnit) {
            base.Channel.CreateDiscountForProductcategory(CategoryID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task CreateDiscountForProductcategoryAsync(int CategoryID, int discountID, int percentUnit) {
            return base.Channel.CreateDiscountForProductcategoryAsync(CategoryID, discountID, percentUnit);
        }
        
        public void CreateDiscountForProducttype(int typeID, int discountID, int percentUnit) {
            base.Channel.CreateDiscountForProducttype(typeID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task CreateDiscountForProducttypeAsync(int typeID, int discountID, int percentUnit) {
            return base.Channel.CreateDiscountForProducttypeAsync(typeID, discountID, percentUnit);
        }
        
        public void UpdateDiscountForProductgroup(int groupID, int discountID, int percentUnit) {
            base.Channel.UpdateDiscountForProductgroup(groupID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task UpdateDiscountForProductgroupAsync(int groupID, int discountID, int percentUnit) {
            return base.Channel.UpdateDiscountForProductgroupAsync(groupID, discountID, percentUnit);
        }
        
        public void UpdateDiscountForProductcategory(int CategoryID, int discountID, int percentUnit) {
            base.Channel.UpdateDiscountForProductcategory(CategoryID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task UpdateDiscountForProductcategoryAsync(int CategoryID, int discountID, int percentUnit) {
            return base.Channel.UpdateDiscountForProductcategoryAsync(CategoryID, discountID, percentUnit);
        }
        
        public void UpdateDiscountForProducttype(int typeID, int discountID, int percentUnit) {
            base.Channel.UpdateDiscountForProducttype(typeID, discountID, percentUnit);
        }
        
        public System.Threading.Tasks.Task UpdateDiscountForProducttypeAsync(int typeID, int discountID, int percentUnit) {
            return base.Channel.UpdateDiscountForProducttypeAsync(typeID, discountID, percentUnit);
        }
        
        public void DeleteDiscountForProductgroup(int groupID, int discountID) {
            base.Channel.DeleteDiscountForProductgroup(groupID, discountID);
        }
        
        public System.Threading.Tasks.Task DeleteDiscountForProductgroupAsync(int groupID, int discountID) {
            return base.Channel.DeleteDiscountForProductgroupAsync(groupID, discountID);
        }
        
        public void DeleteDiscountForProductcategory(int CategoryID, int discountID) {
            base.Channel.DeleteDiscountForProductcategory(CategoryID, discountID);
        }
        
        public System.Threading.Tasks.Task DeleteDiscountForProductcategoryAsync(int CategoryID, int discountID) {
            return base.Channel.DeleteDiscountForProductcategoryAsync(CategoryID, discountID);
        }
        
        public void DeleteDiscountForProducttype(int typeID, int discountID) {
            base.Channel.DeleteDiscountForProducttype(typeID, discountID);
        }
        
        public System.Threading.Tasks.Task DeleteDiscountForProducttypeAsync(int typeID, int discountID) {
            return base.Channel.DeleteDiscountForProducttypeAsync(typeID, discountID);
        }
        
        public SoapToRest.DiscountService.DiscountInfo[] GetOrganisationDiscounts(int organisationID) {
            return base.Channel.GetOrganisationDiscounts(organisationID);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo[]> GetOrganisationDiscountsAsync(int organisationID) {
            return base.Channel.GetOrganisationDiscountsAsync(organisationID);
        }
        
        public SoapToRest.DiscountService.Product[] GetADiscountsProducts(int DiscountID) {
            return base.Channel.GetADiscountsProducts(DiscountID);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.DiscountService.Product[]> GetADiscountsProductsAsync(int DiscountID) {
            return base.Channel.GetADiscountsProductsAsync(DiscountID);
        }
        
        public void CreateDiscount(SoapToRest.DiscountService.DiscountInfo Discount) {
            base.Channel.CreateDiscount(Discount);
        }
        
        public System.Threading.Tasks.Task CreateDiscountAsync(SoapToRest.DiscountService.DiscountInfo Discount) {
            return base.Channel.CreateDiscountAsync(Discount);
        }
        
        public void EditDiscount(SoapToRest.DiscountService.DiscountInfo Discount) {
            base.Channel.EditDiscount(Discount);
        }
        
        public System.Threading.Tasks.Task EditDiscountAsync(SoapToRest.DiscountService.DiscountInfo Discount) {
            return base.Channel.EditDiscountAsync(Discount);
        }
        
        public void DeleteDiscount(int ID) {
            base.Channel.DeleteDiscount(ID);
        }
        
        public System.Threading.Tasks.Task DeleteDiscountAsync(int ID) {
            return base.Channel.DeleteDiscountAsync(ID);
        }
        
        public SoapToRest.DiscountService.DiscountInfo[] GetDiscounts() {
            return base.Channel.GetDiscounts();
        }
        
        public System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo[]> GetDiscountsAsync() {
            return base.Channel.GetDiscountsAsync();
        }
        
        public SoapToRest.DiscountService.DiscountInfo GetDiscount(int ID) {
            return base.Channel.GetDiscount(ID);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.DiscountService.DiscountInfo> GetDiscountAsync(int ID) {
            return base.Channel.GetDiscountAsync(ID);
        }
    }
}
