//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapToRest.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapToRest.ProductService.ProductHasAttribute[] attributeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int categoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int groupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapToRest.ProductService.ProductHasAttribute[] attributeList {
            get {
                return this.attributeListField;
            }
            set {
                if ((object.ReferenceEquals(this.attributeListField, value) != true)) {
                    this.attributeListField = value;
                    this.RaisePropertyChanged("attributeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                if ((this.categoryIdField.Equals(value) != true)) {
                    this.categoryIdField = value;
                    this.RaisePropertyChanged("categoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string group {
            get {
                return this.groupField;
            }
            set {
                if ((object.ReferenceEquals(this.groupField, value) != true)) {
                    this.groupField = value;
                    this.RaisePropertyChanged("group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int groupId {
            get {
                return this.groupIdField;
            }
            set {
                if ((this.groupIdField.Equals(value) != true)) {
                    this.groupIdField = value;
                    this.RaisePropertyChanged("groupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int typeId {
            get {
                return this.typeIdField;
            }
            set {
                if ((this.typeIdField.Equals(value) != true)) {
                    this.typeIdField = value;
                    this.RaisePropertyChanged("typeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductHasAttribute", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class ProductHasAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int attributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int attributeId {
            get {
                return this.attributeIdField;
            }
            set {
                if ((this.attributeIdField.Equals(value) != true)) {
                    this.attributeIdField = value;
                    this.RaisePropertyChanged("attributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceReport", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class PriceReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurrenceDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int businessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurrenceDT {
            get {
                return this.OccurrenceDTField;
            }
            set {
                if ((this.OccurrenceDTField.Equals(value) != true)) {
                    this.OccurrenceDTField = value;
                    this.RaisePropertyChanged("OccurrenceDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int businessId {
            get {
                return this.businessIdField;
            }
            set {
                if ((this.businessIdField.Equals(value) != true)) {
                    this.businessIdField = value;
                    this.RaisePropertyChanged("businessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productGroupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productGroupId {
            get {
                return this.productGroupIdField;
            }
            set {
                if ((this.productGroupIdField.Equals(value) != true)) {
                    this.productGroupIdField = value;
                    this.RaisePropertyChanged("productGroupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productCategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productCategoryId {
            get {
                return this.productCategoryIdField;
            }
            set {
                if ((this.productCategoryIdField.Equals(value) != true)) {
                    this.productCategoryIdField = value;
                    this.RaisePropertyChanged("productCategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://schemas.datacontract.org/2004/07/WcfProduct.Data")]
    [System.SerializableAttribute()]
    public partial class Attribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        SoapToRest.ProductService.Product[] GetAllProducts(bool showDiscounted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllProducts", ReplyAction="http://tempuri.org/IProductService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Product[]> GetAllProductsAsync(bool showDiscounted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductDetails", ReplyAction="http://tempuri.org/IProductService/GetProductDetailsResponse")]
        SoapToRest.ProductService.Product GetProductDetails(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductDetails", ReplyAction="http://tempuri.org/IProductService/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Product> GetProductDetailsAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsFromCompany", ReplyAction="http://tempuri.org/IProductService/GetProductsFromCompanyResponse")]
        SoapToRest.ProductService.Product[] GetProductsFromCompany(int businessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductsFromCompany", ReplyAction="http://tempuri.org/IProductService/GetProductsFromCompanyResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Product[]> GetProductsFromCompanyAsync(int businessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPricesFromProduct", ReplyAction="http://tempuri.org/IProductService/GetPricesFromProductResponse")]
        SoapToRest.ProductService.PriceReport[] GetPricesFromProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPricesFromProduct", ReplyAction="http://tempuri.org/IProductService/GetPricesFromProductResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.PriceReport[]> GetPricesFromProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPricesFromProductAtCompany", ReplyAction="http://tempuri.org/IProductService/GetPricesFromProductAtCompanyResponse")]
        SoapToRest.ProductService.PriceReport[] GetPricesFromProductAtCompany(int productId, int businessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetPricesFromProductAtCompany", ReplyAction="http://tempuri.org/IProductService/GetPricesFromProductAtCompanyResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.PriceReport[]> GetPricesFromProductAtCompanyAsync(int productId, int businessId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductGroups", ReplyAction="http://tempuri.org/IProductService/GetProductGroupsResponse")]
        SoapToRest.ProductService.Group[] GetProductGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductGroups", ReplyAction="http://tempuri.org/IProductService/GetProductGroupsResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Group[]> GetProductGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductCategories", ReplyAction="http://tempuri.org/IProductService/GetProductCategoriesResponse")]
        SoapToRest.ProductService.Category[] GetProductCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductCategories", ReplyAction="http://tempuri.org/IProductService/GetProductCategoriesResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Category[]> GetProductCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductTypes", ReplyAction="http://tempuri.org/IProductService/GetProductTypesResponse")]
        SoapToRest.ProductService.Type[] GetProductTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetProductTypes", ReplyAction="http://tempuri.org/IProductService/GetProductTypesResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Type[]> GetProductTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ReportPrice", ReplyAction="http://tempuri.org/IProductService/ReportPriceResponse")]
        bool ReportPrice(SoapToRest.ProductService.PriceReport priceReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ReportPrice", ReplyAction="http://tempuri.org/IProductService/ReportPriceResponse")]
        System.Threading.Tasks.Task<bool> ReportPriceAsync(SoapToRest.ProductService.PriceReport priceReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        void CreateProduct(SoapToRest.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        System.Threading.Tasks.Task CreateProductAsync(SoapToRest.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        void UpdateProduct(SoapToRest.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(SoapToRest.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProduct", ReplyAction="http://tempuri.org/IProductService/DeleteProductResponse")]
        void DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteProduct", ReplyAction="http://tempuri.org/IProductService/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllAttributes", ReplyAction="http://tempuri.org/IProductService/GetAllAttributesResponse")]
        SoapToRest.ProductService.Attribute[] GetAllAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAllAttributes", ReplyAction="http://tempuri.org/IProductService/GetAllAttributesResponse")]
        System.Threading.Tasks.Task<SoapToRest.ProductService.Attribute[]> GetAllAttributesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAttributeName", ReplyAction="http://tempuri.org/IProductService/GetAttributeNameResponse")]
        string GetAttributeName(int attributeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/GetAttributeName", ReplyAction="http://tempuri.org/IProductService/GetAttributeNameResponse")]
        System.Threading.Tasks.Task<string> GetAttributeNameAsync(int attributeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ToggleDiscountOnProduct", ReplyAction="http://tempuri.org/IProductService/ToggleDiscountOnProductResponse")]
        bool ToggleDiscountOnProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ToggleDiscountOnProduct", ReplyAction="http://tempuri.org/IProductService/ToggleDiscountOnProductResponse")]
        System.Threading.Tasks.Task<bool> ToggleDiscountOnProductAsync(int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : SoapToRest.ProductService.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<SoapToRest.ProductService.IProductService>, SoapToRest.ProductService.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoapToRest.ProductService.Product[] GetAllProducts(bool showDiscounted) {
            return base.Channel.GetAllProducts(showDiscounted);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Product[]> GetAllProductsAsync(bool showDiscounted) {
            return base.Channel.GetAllProductsAsync(showDiscounted);
        }
        
        public SoapToRest.ProductService.Product GetProductDetails(int productId) {
            return base.Channel.GetProductDetails(productId);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Product> GetProductDetailsAsync(int productId) {
            return base.Channel.GetProductDetailsAsync(productId);
        }
        
        public SoapToRest.ProductService.Product[] GetProductsFromCompany(int businessId) {
            return base.Channel.GetProductsFromCompany(businessId);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Product[]> GetProductsFromCompanyAsync(int businessId) {
            return base.Channel.GetProductsFromCompanyAsync(businessId);
        }
        
        public SoapToRest.ProductService.PriceReport[] GetPricesFromProduct(int productId) {
            return base.Channel.GetPricesFromProduct(productId);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.PriceReport[]> GetPricesFromProductAsync(int productId) {
            return base.Channel.GetPricesFromProductAsync(productId);
        }
        
        public SoapToRest.ProductService.PriceReport[] GetPricesFromProductAtCompany(int productId, int businessId) {
            return base.Channel.GetPricesFromProductAtCompany(productId, businessId);
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.PriceReport[]> GetPricesFromProductAtCompanyAsync(int productId, int businessId) {
            return base.Channel.GetPricesFromProductAtCompanyAsync(productId, businessId);
        }
        
        public SoapToRest.ProductService.Group[] GetProductGroups() {
            return base.Channel.GetProductGroups();
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Group[]> GetProductGroupsAsync() {
            return base.Channel.GetProductGroupsAsync();
        }
        
        public SoapToRest.ProductService.Category[] GetProductCategories() {
            return base.Channel.GetProductCategories();
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Category[]> GetProductCategoriesAsync() {
            return base.Channel.GetProductCategoriesAsync();
        }
        
        public SoapToRest.ProductService.Type[] GetProductTypes() {
            return base.Channel.GetProductTypes();
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Type[]> GetProductTypesAsync() {
            return base.Channel.GetProductTypesAsync();
        }
        
        public bool ReportPrice(SoapToRest.ProductService.PriceReport priceReport) {
            return base.Channel.ReportPrice(priceReport);
        }
        
        public System.Threading.Tasks.Task<bool> ReportPriceAsync(SoapToRest.ProductService.PriceReport priceReport) {
            return base.Channel.ReportPriceAsync(priceReport);
        }
        
        public void CreateProduct(SoapToRest.ProductService.Product product) {
            base.Channel.CreateProduct(product);
        }
        
        public System.Threading.Tasks.Task CreateProductAsync(SoapToRest.ProductService.Product product) {
            return base.Channel.CreateProductAsync(product);
        }
        
        public void UpdateProduct(SoapToRest.ProductService.Product product) {
            base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(SoapToRest.ProductService.Product product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        public void DeleteProduct(int productId) {
            base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int productId) {
            return base.Channel.DeleteProductAsync(productId);
        }
        
        public SoapToRest.ProductService.Attribute[] GetAllAttributes() {
            return base.Channel.GetAllAttributes();
        }
        
        public System.Threading.Tasks.Task<SoapToRest.ProductService.Attribute[]> GetAllAttributesAsync() {
            return base.Channel.GetAllAttributesAsync();
        }
        
        public string GetAttributeName(int attributeId) {
            return base.Channel.GetAttributeName(attributeId);
        }
        
        public System.Threading.Tasks.Task<string> GetAttributeNameAsync(int attributeId) {
            return base.Channel.GetAttributeNameAsync(attributeId);
        }
        
        public bool ToggleDiscountOnProduct(int productId) {
            return base.Channel.ToggleDiscountOnProduct(productId);
        }
        
        public System.Threading.Tasks.Task<bool> ToggleDiscountOnProductAsync(int productId) {
            return base.Channel.ToggleDiscountOnProductAsync(productId);
        }
    }
}
